title: "My G Site"
description: "A Jekyll + Tailwind starter"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://GilbertoTorres.github.io" # your GitHub Pages URL

theme: jekyll-theme-primer

# Markdown and permalink settings
markdown: kramdown
permalink: pretty

# Exclude files and folders that should not be processed by Jekyll
exclude:
  - node_modules
  - vendor
  - package.json
  - package-lock.json
  - webpack.config.js
  - tailwind.config.js
  - postcss.config.js
  - netlify.toml
  - README.md
  - LICENSE

# Include (if you want Jekyll to copy these without processing)
include:
  - assets

plugins:
  - jekyll-seo-tag
  - jekyll-feed
